//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketBooking.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("MovieBooking.Action")]
    public partial class Horror
    {
        [Key]
        public string MovieName { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string Description { get; set; }
    }
}
