//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTicketBooking.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
  

    [Table("MovieBooking.Action")]

    public partial class Payment
    {
        [Key]

        [Required(ErrorMessage = "ID is Required")]
        [RegularExpression(@"[A-Z]+[a-z]*", ErrorMessage = "Only 3 digits allowed")]
        public string Name { get; set; }


        [Required(ErrorMessage = "Email is Required")]
        [RegularExpression(@"[A-Z]+[a-z]*", ErrorMessage = "Specified format")]
        public string email { get; set; }
        [StringLength(30, ErrorMessage = "Name is required")]
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }

        [Required(ErrorMessage = "Zip is Required")]
        [RegularExpression(@"[0-9]{6}", ErrorMessage = "Only 3 digits allowed")]
        public Nullable<int> zip { get; set; }
        public string cardName { get; set; }

        [Required(ErrorMessage = "CardNumber is Required")]
        [RegularExpression(@"[0-9]{4}[-][0-9]{4}[-][0-9]{4}[-][0-9]{4}", ErrorMessage = "Specified format only")]
        public Nullable<long> cardNumber { get; set; }

        [Required(ErrorMessage = "Date is Required")]
        [RegularExpression(@"[0-9]{4}", ErrorMessage = "Date in specified format")]
        public Nullable<System.DateTime> expYear { get; set; }

        [Required(ErrorMessage = "cvv is Required")]
        [RegularExpression(@"[0-9]{3}", ErrorMessage = "Only 3 digits allowed")]
        public Nullable<int> Cvv { get; set; }
    }
}
